version: '3.0'

volumes:
  pg-db:

services:
  db-pet:
    image: postgres:15.5-alpine
    container_name: pet
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pg-db:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready-U admin']
      interval: 30s
      timeout: 10s
      retries: 3
